In [1]:
import numpy as np
import pandas as pd

In [21]:
np.corrcoef([5,3,4,4],[3,3,1,5])

array([[1., 0.],
       [0., 1.]])

In [15]:
nr=(3-2.25)*(3-2.25)+(5-3.5)*(3-3.5)+(4-3)*(5-3)+(1-3.25)*(2-3.25)
nr


4.625

In [16]:
dr=(np.sqrt((3-2.25)**2+(5-3.5)**2+(4-3)**2+(1-3.25)**2))*(np.sqrt((3-2.25)**2+(3-3.5)**2+(5-3)**2+(2-3.25)**2))

In [17]:
dr

7.521843191665191

In [18]:
nr/dr

0.6148758864216782

In [30]:
R=np.array([[1.0,2.0,3.0,5.0],[2,0,8,12],[3,6,7,13]])
R1=pd.DataFrame(R)

In [31]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R1, k = 2)

In [32]:
U

array([[ 0.1463177 ,  0.2789851 ],
       [-0.76768943,  0.63710454],
       [ 0.62389428,  0.71851591]])

In [33]:
Vt

array([[ 0.11238294,  0.93982037, -0.31093759, -0.0861717 ],
       [ 0.16660877,  0.2187343 ,  0.4925118 ,  0.82572935]])

In [34]:
sigma

array([ 4.29443878, 22.26018363])

In [2]:
np.dot([5,3,4,4],[1,5,5,2])

48

In [4]:
(np.sqrt(5**2+3**2+4**2+4**2))*(np.sqrt(1**2+5**2+5**2+2**2))

60.249481325568276

In [5]:
48/60.249

0.7966937210576109

In [22]:
4+((0.85*(3-2.25)+.70*(5-3.5)+0*(4-3)+0.79*(1-3.25))/(0.85+0.7+0.79))

3.9615384615384612

In [23]:
4+((0.85*(3-2.25)+.70*(5-3.5)+0*(4-3)-0.79*(1-3.25))/(0.85+0.7-0.79))

8.559210526315791

In [19]:
.58*5+.478*3+.43*4+.58*4/(.58+.478+.43+.58)

7.175856866537718